spring.application.name=PaymentOrchestrator

spring.datasource.url=jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1908

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

gateway.razorpay.latency-ms=200
gateway.razorpay.success-rate=0.90
gateway.razorpay.timeout-rate=0.02
gateway.razorpay.max-latency-ms=3000

gateway.stripe.latency-ms=1500
gateway.stripe.success-rate=0.60
gateway.stripe.timeout-rate=0.10
gateway.stripe.max-latency-ms=3000


gateway.upi.latency-ms=100
gateway.upi.success-rate=0.95
gateway.upi.timeout-rate=0.01
gateway.upi.max-latency-ms=3000